### ISSUE TITLE
Package for Conda Forge

### ISSUE THREAD

**Issue by captivus** [CyanBook/spotipy2#8]
Hello!  I tried to package for Conda Forge using the source that you've made available with the PyPI package you distribute.  There is, however, an issue with the tarball provided at PyPI which results in failed builds.  (Specifically, setup.py bombs out because it references a missing requirements.txt file.)  Rather than try to work around that, I've packaged spotipy2for Conda Forge using this GitHub repo as source.  

I'm pleased to say that the package has been accepted and is available in Conda Forge.

Cheers!

**Comment by CyanBook** [comment]
Can you link me the package on Conda Forge? Is there anything I can do to fix this missing requirements.txt file?

**Comment by captivus** [comment]
Sure, it's here:  https://github.com/conda-forge/spotipy2-feedstock.  You can also see that it's installable from the repo here:

![image](https://user-images.githubusercontent.com/366332/177358502-830b2f44-897c-4bab-b7dc-6cea877a85ed.png)

For some reason, the package list on the conda-forge.org website still hasn't updated, but it's packaged and installable.

Re your question on the requirements.txt issue, the version you have in the GitHub repo builds successfully (as setup.py correctly references the requirements.txt that you have bundled in the repo) so I'd suggest pushing the latest GitHub version to PyPI.  As the Conda Forge feedstock is working as packaged directly from your GitHub repo, I likely won't repackage it from the PyPI repo unless there is a compelling reason to do so.

**Comment by CyanBook** [comment]
Thanks, Iet me know if you encounter any issues with spotipy2!
